name: "🐛 Bug Report"
description: Something isn’t working right
title: "[Bug]: "
labels: [bug]
body:
  - type: select
    id: association
    attributes:
      label: Association
      description: Select the applicable association.
      options:
        - DTFB (DE)
        - TFVHH (DE)
        - NTFV (DE)
        - NWTFV (DE)
        - MTFV (DE)
        - TFVB (DE)
        - TFVSH (DE)
        - STFV (DE)
        - NTVB (NL)
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the issue clearly and simply.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Tell us how to trigger the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: input
    id: platform
    attributes:
      label: Platform / Device / OS
      description: E.g. Android 14, iOS 17, Web, Chrome 125, etc.
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or logs (optional)
    validations:
      required: false
