name: "💡 Feature Request"
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: What's your idea?
      description: Describe the feature or improvement.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Why is this needed?
      description: Describe the problem this would solve or the benefit it provides.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or other ideas?
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional notes (optional)
    validations:
      required: false

